"""Add Batches and Enrollments

Revision ID: b63c1b96af4b
Revises: 
Create Date: 2026-08-29 20:57:52.333066
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b63c1b96af4b'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    import sqlalchemy as sa_inner
    bind = op.get_bind()
    inspector = sa_inner.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'batch_enrollments' not in existing_tables:
        op.create_table('batch_enrollments',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('batch_id', sa.Text(), nullable=False),
        sa.Column('student_id', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='batch_enrollments_pkey')
        )
    if 'batches' not in existing_tables:
        op.create_table('batches',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('tenant_id', sa.Text(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='batches_pkey')
        )
    if 'course_batches' not in existing_tables:
        op.create_table('course_batches',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('course_id', sa.Text(), nullable=False),
        sa.Column('batch_id', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='course_batches_pkey')
        )

    # Add teacher_id only if it doesn't exist yet
    existing_cols = [c['name'] for c in inspector.get_columns('courses')]
    if 'teacher_id' not in existing_cols:
        op.add_column('courses', sa.Column('teacher_id', sa.Text(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'teacher_id')
    op.drop_table('course_batches')
    op.drop_table('batches')
    op.drop_table('batch_enrollments')
    # ### end Alembic commands ###
